# Generated by Django 4.0.5 on 2022-06-04 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=200)),
                ('manufacture_year', models.IntegerField()),
                ('engine_power', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=200)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=6)),
                ('street', models.CharField(max_length=250)),
                ('street_number', models.CharField(max_length=10)),
                ('flat_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.customer')),
            ],
        ),
    ]
